baseURL = 'https://www.daucloud.com/'
languageCode = 'en-US'
Title = 'Daucloud'
theme = "void"
defaultContentLanguage = "en"
relativeURLs = true
canonifyURLs = true

# 社交媒体链接
[params]
  [params.social]
    github = "https://github.com/Daucloud"
    zhihu = "https://zhihu.com/people/daucloud"
    email = "1311700152@qq.com"
  [params.avatar]
    url = "https://img.picgo.net/2025/03/23/20250323133122762dc0742d658f46dec.jpeg"
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight =  20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40


[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[languages]
  [languages.zh]
    languageName = "中文"
    weight = 2
    title = "Daucloud's Blog"
    description = "分享知识、经验和想法"
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Daucloud's Blog"
    description = "Share knowledge, experience, and ideas"

[caches]
  [caches.images]
    dir = ':cacheDir/images'